#!/usr/bin/env bash
existing_filepath="$1"
target_filepath="$2"

# 
# Get virkshop config
# 
path_to_virkshop_config=""
file_name="virkshop/internals/configuration"
folder_to_look_in="$PWD"
while :
do
    # check if file exists
    if [ -f "$folder_to_look_in/$file_name" ]
    then
        path_to_virkshop_config="$folder_to_look_in/$file_name"
        break
    else
        if [ "$folder_to_look_in" = "/" ]
        then
            break
        else
            folder_to_look_in="$(dirname "$folder_to_look_in")"
        fi
    fi
done
if [ -z "$path_to_virkshop_config" ]
then
    #
    # what to do if file never found
    #
    echo "$(yellow)"
    echo "|-- Problem -------------------------------------------------------------| $(color_reset)" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|    Looks like you have nix installed (that's good)                     |" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|    However, I can't find the virkshop/internals/configuration folder   |" 1>&2
    echo "|    I started looking in your current folder                            |" 1>&2
    echo "|         current directory is: '$PWD'                                 " 1>&2
    echo "|    I also looked in all the parent folders, but couldn't find it       |" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|    todo:                                                               |" 1>&2
    echo "|      - make sure you're in the right folder (likely to be the problem) |" 1>&2
    echo "|      - make sure the virkshop folder isn't corrupted (re-download)     |" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|------------------------------------------------------------------------|" 1>&2
    echo ""
    # TODO: in the future, offer to redownload (encase the script is being run directly from curl)
    # TODO: in the future, check if already inside of a virkshop (accidentally doing virkshop inception)
    exit
fi
path_to_project="$path_to_virkshop_config/../../.."
path_to_virkshop="$path_to_virkshop_config/../../"
path_to_virkshop_entry="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/entry_point")"
path_to_virkshop_temp="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/temporary")"
path_to_virkshop_tools="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/core_tools")"
path_to_commands="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/commands")"
path_to_documentation="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/documentation")"
path_to_events="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/events")"
path_to_settings="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/settings")"
path_to_mixins="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/mixins")"

# 
# make existing_filepath absolute
# 
case "$existing_filepath" in
    # if absolute
    /*) : ;;
    # if relative
    *) existing_filepath="$path_to_project/$existing_filepath" ;;
esac

# 
# make target_filepath absolute
# 
case "$target_filepath" in
    # if absolute
    /*) : ;;
    # if relative
    *) target_filepath="$path_to_project/$target_filepath" ;;
esac

# remove existing things in the way
rm -f "$target_filepath" 2>/dev/null
rm -rf "$target_filepath" 2>/dev/null
# make sure parent folder exists
mkdir -p "$(dirname "$target_filepath")"
__temp_var__relative_part="$(realpath "$(dirname "$existing_filepath")" --relative-to="$(dirname "$target_filepath")" --canonicalize-missing)"
__temp_var__relative_path="$__temp_var__relative_part/$(basename "$existing_filepath")"
# link using the relative path
if [ -d "$existing_filepath" ]
then
    ln -s "$__temp_var__relative_path/" "$target_filepath"
else
    ln -s "$__temp_var__relative_path" "$target_filepath"
fi
unset __temp_var__relative_path
unset __temp_var__relative_part
unset existing_filepath
unset target_filepath