#!/usr/bin/env -S deno run --allow-all

// 
// main
// 
const oldFolder = Deno.args[0]
const incomingFolder = Deno.args[1]
function main() {
    safeRecursiveLinkedMerge({ oldFolder, incomingFolder })
}


// 
// helpers
// 
const Path = await import("https://deno.land/std@0.117.0/path/mod.ts")
const { copy } = await import("https://deno.land/std@0.123.0/streams/conversion.ts")
const FileSystem = {
    get cwd() {
        return Deno.cwd()
    },
    info: async (fileOrFolder) => {
        const result1 = await Deno.lstat(fileOrFolder).catch(()=>({doesntExist: true}))
        result1.exists = !result1.doesntExist
        if (result1.exists) {
            const result2 = await Deno.stat(fileOrFolder).catch(()=>({doesntExist: true}))
            result1.isFile = result2.isFile
            result1.isDirectory = result2.isDirectory
        }
        return result1
    },
    remove: (fileOrFolder) => Deno.remove(path,{recursive: true}).catch(()=>false),
    makeAbsolute: (path)=> {
        if (!Path.isAbsolute(path)) {
            return Path.normalize(Path.join(Deno.cwd(), path))
        } else {
            return path
        }
    },
    clearAPathFor: (path)=>{
        const parentPath = Path.dirname(path)
        // dont need to clear a path for the root folder
        if (parentPath == path) {
            return
        } else {
            // we do need to clear a path for the parent of this folder
            FileSystem.clearAPathFor(parentPath)
        }
        const { exists, isDirectory } = FileSystem.info(parentPath)
        // if a folder is in the way, delete it
        if (exists && !isDirectory) {
            await FileSystem.remove(parentPath)
        }
        const parentPath = await Deno.lstat(parentPath).catch(()=>({doesntExist: true}))
        // if no folder was there, create one
        if (!parentPath.exists) {
            Deno.mkdir(Path.dirname(parentPath),{ recursive: true })
        }
    },
    copy: async ({from, to, force=true}) => {
        FileSystem.clearAPathFor(to)
        if (force) {
            FileSystem.remove(to)
        }
        const source = await Deno.open(from, { read: true })
        const target = await Deno.create(to)
        result = await copy(source, target)
        Deno.close(source.rid)
        Deno.close(target.rid)
        return result
    },
    relativeLink: ({existingItem, newItem}) => {
        const cwd = Deno.cwd()
        existingItem = Deno.relative(Deno.cwd(), Path.normalize(existingItem))
        newItem = Deno.relative(Deno.cwd(), Path.normalize(newItem))
        const existingItemDoesntExist = (await Deno.stat(parentPath).catch(()=>({doesntExist: true}))).doesntExist
        // if the item doesnt exists
        if (existingItemDoesntExist) {
            // FIXME: cause an error
        } else {
            FileSystem.clearAPathFor(newItem)
            FileSystem.remove(newItem)
        }
        return Deno.symlink(existingItem, newItem)
    },
    // todo: should probably make this an async generator
    recursiveFileList: async (path, options)=> {
        if (!options.alreadySeached) {
            options.alreadySeached = new Set()
        }
        // avoid infinite loops
        if (alreadySeached.has(path)) {
            return []
        }
        const absolutePathVersion = FileSystem.makeAbsolute(path)
        alreadySeached.add(absolutePathVersion)
        const results = []
        for await (const dirEntry of Deno.readDir(path)) {
            const eachPath = Path.join(path, dirEntry.name)
            if (dirEntry.isFile) {
                results.push(eachPath)
            } else if (dirEntry.isDirectory) {
                for (const each of await FileSystem.recursiveFileList(eachPath, {...options, alreadySeached})) {
                    results.push(each)
                }
            } else if (!options.onlyHardlinks && dirEntry.isSymlink) {
                if (options.dontFollowSymlinks) {
                    results.push(eachPath)
                } else {
                    const pathInfo = await Deno.stat(eachPath).catch(()=>({doesntExist: true}))
                    if (pathInfo.isDirectory) {
                        for (const each of await FileSystem.recursiveFileList(eachPath, {...options, alreadySeached})) {
                            results.push(each)
                        }
                    } else {
                        results.push(eachPath)
                    }
                }
            }
        }
        return results
    },
}

const safeRecursiveLinkedMerge = async ({oldFolder, incomingFolder}) => {
    const oldFolderInfo = await FileSystem.info(oldFolder)
    const incomingFolderInfo = await FileSystem.info(incomingFolder)
    if (oldFolderInfo.isFile || incomingFolderInfo.isFile) {
        return
    }
    if (incomingFolderInfo.doesntExist) {
        return
    }
    if (oldFolderInfo.doesntExist) {
        Deno.mkdir(oldFolder,{ recursive: true })
    }
    for (const each of Deno.readDir(incomingFolder)) {
        const existingPath = Path.join(incomingFolder, each.name)
        const targetPath   = Path.join(oldFolder, each.name)
        const targetPathInfo = FileSystem.info(targetPath)
        // 
        // shallow part
        // 
        if (each.isFile) {
            // dont overwrite (only perform if it doesnt exist)
            if (!FileSystem.info(targetPath).exists)  {
                FileSystem.relativeLink({existingItem: existingPath, newItem: targetPath })
            } else {
                // Todo: should probably do something like return which ones were skipped so they can be reported
            }
            continue
        }
        // 
        // recursive part
        // 
        const existingPathInfo = FileSystem.info(existingPath)
        if (existingPathInfo.isDirectory) {
            // create a folder if it doesn't exist
            if (!targetPathInfo.isDirectory) {
                Deno.mkdir(targetPath,{ recursive: true })
            }
            // recursion
            safeRecursiveLinkedMerge({oldFolder: targetPath, incomingFolder: existingPath})
        }
    }
}

// 
// run main
// 
main()