#!/usr/bin/env -S deno run --allow-all
import { FileSystem } from "https://deno.land/x/quickr@0.6.6/main/file_system.js"
import { run, throwIfFails, zipInto, mergeInto, returnAsString, Timeout, Env, Cwd, Stdin, Stdout, Stderr, Out, Overwrite, AppendTo } from "https://deno.land/x/quickr@0.6.6/main/run.js"
const { virkshop } = await FileSystem.walkUpImport("virkshop.js")

// cd to the main folder
FileSystem.pwd = `${virkshop.pathTo.project}/main`

const distName = "dist"
await FileSystem.remove(distName)
await run`python setup.py sdist bdist_wheel`
const info = await FileSystem.info(distName)
if (info.isFolder) {
    const pathsForTwine = (await FileSystem.listPathsIn(distName)).map(each=>`${distName}/${each}`)
    await run("twine", "upload", ...pathsForTwine)
}