#!/usr/bin/env bash


# 
# Get virkshop config
# 
    path_to_virkshop_config=""
    file_name="virkshop/internals/configuration"
    folder_to_look_in="$PWD"
    while :
    do
        # check if file exists
        if [ -f "$folder_to_look_in/$file_name" ]
        then
            path_to_virkshop_config="$folder_to_look_in/$file_name"
            break
        else
            if [ "$folder_to_look_in" = "/" ]
            then
                break
            else
                folder_to_look_in="$(dirname "$folder_to_look_in")"
            fi
        fi
    done
    if [ -z "$path_to_virkshop_config" ]
    then
        #
        # what to do if file never found
        #
        echo "$(yellow)"
        echo "|-- Problem -------------------------------------------------------------| $(color_reset)" 1>&2
        echo "|                                                                        |" 1>&2
        echo "|    Looks like you have nix installed (that's good)                     |" 1>&2
        echo "|                                                                        |" 1>&2
        echo "|    However, I can't find the virkshop/internals/configuration folder   |" 1>&2
        echo "|    I started looking in your current folder                            |" 1>&2
        echo "|         current directory is: '$PWD'                                 " 1>&2
        echo "|    I also looked in all the parent folders, but couldn't find it       |" 1>&2
        echo "|                                                                        |" 1>&2
        echo "|    todo:                                                               |" 1>&2
        echo "|      - make sure you're in the right folder (likely to be the problem) |" 1>&2
        echo "|      - make sure the virkshop folder isn't corrupted (re-download)     |" 1>&2
        echo "|                                                                        |" 1>&2
        echo "|------------------------------------------------------------------------|" 1>&2
        echo ""
        # TODO: in the future, offer to redownload (encase the script is being run directly from curl)
        # TODO: in the future, check if already inside of a virkshop (accidentally doing virkshop inception)
        exit
    fi
    export VIRKSHOP_FOLDER="$(dirname "$(dirname "$path_to_virkshop_config")")"
    path_to_virkshop_tools="$VIRKSHOP_FOLDER/$(cat "$path_to_virkshop_config/path_to/core_tools")"


"$path_to_virkshop_tools/actions/trigger" "$VIRKSHOP_FOLDER/events/$1"