#!/usr/bin/env bash

# 
# Get virkshop config
# 
    path_to_virkshop_config=""
    file_name="virkshop/mixins/#core/settings/virkshop/"
    folder_to_look_in="$PWD"
    while :
    do
        # check if file exists
        if [ -f "$folder_to_look_in/$file_name" ]
        then
            path_to_virkshop_config="$folder_to_look_in/$file_name"
            break
        else
            if [ "$folder_to_look_in" = "/" ]
            then
                break
            else
                folder_to_look_in="$(dirname "$folder_to_look_in")"
            fi
        fi
    done
    if [ -z "$path_to_virkshop_config" ]
    then
        #
        # what to do if file never found
        #
        echo "$(yellow)"
        echo "|-- Problem -------------------------------------------------------------| $(color_reset)" 1>&2
        echo "|                                                                        |" 1>&2
        echo "|    Looks like you have nix installed (that's good)                     |" 1>&2
        echo "|                                                                        |" 1>&2
        echo "|    However, I can't find the virkshop/mixins/#core/settings/virkshop/ folder   |" 1>&2
        echo "|    I started looking in your current folder                            |" 1>&2
        echo "|         current directory is: '$PWD'                                 " 1>&2
        echo "|    I also looked in all the parent folders, but couldn't find it       |" 1>&2
        echo "|                                                                        |" 1>&2
        echo "|    todo:                                                               |" 1>&2
        echo "|      - make sure you're in the right folder (likely to be the problem) |" 1>&2
        echo "|      - make sure the virkshop folder isn't corrupted (re-download)     |" 1>&2
        echo "|                                                                        |" 1>&2
        echo "|------------------------------------------------------------------------|" 1>&2
        echo ""
        # TODO: in the future, offer to redownload (encase the script is being run directly from curl)
        # TODO: in the future, check if already inside of a virkshop (accidentally doing virkshop inception)
        exit
    fi
    path_to_project="$path_to_virkshop_config/../../.."
    path_to_virkshop="$path_to_virkshop_config/../../"
    path_to_virkshop_entry="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/entry_point")"
    path_to_virkshop_temp="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/temporary")"
    path_to_virkshop_tools="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/core_tools")"
    path_to_commands="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/commands")"
    path_to_documentation="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/documentation")"
    path_to_events="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/events")"
    path_to_settings="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/settings")"
    path_to_mixins="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/mixins")"
    path_to_home="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/home")"
    path_to_temp_home="$path_to_virkshop/$(cat "$path_to_virkshop_config/path_to/temporary_home")"
    
    export VIRKSHOP_FOLDER="$(dirname "$(dirname "$path_to_virkshop_config")")"
    export VIRKSHOP_DEBUG="$path_to_virkshop/$(cat "$path_to_virkshop_config/debugging_mode")"

    relative_link="$path_to_virkshop_tools/file_tools/relative_link"
    safe_recursive_linked_merge="$path_to_virkshop_tools/file_tools/safe_recursive_linked_merge"
    trigger="$path_to_virkshop_tools/actions/trigger"

# 
# 
# [ actual program code here ]
# 
# 