#!/usr/bin/env -S bash --noprofile --norc
# yes this is a terribly round-about way to disable profiles, but its currently the only way AFAIK
dontAddDisableDepTrack=1;
[ -e $stdenv/setup ] && source $stdenv/setup;
set +e;
[ -n "$PS1" ] && PS1='\n\[\033[1;32m\][nix-shell:\w]\$\[\033[0m\] ';
if [ "$(type -t runHook)" = function ];
then
    runHook shellHook;
fi;
unset NIX_ENFORCE_PURITY;
shopt -u nullglob;
unset TZ;
zsh --no-globalrcs
exit