#!/usr/bin/env -S deno run --allow-all
import { FileSystem } from "https://deno.land/x/quickr@0.6.13/main/file_system.js"
const { virkshop } = await FileSystem.walkUpImport("virkshop/@core/virkshop")
import "./clean" // first clean

await virkshop.trigger(`project/purge`) // run all the files inside virkshop/events/project/purge