#!/usr/bin/env -S bash --norc --noprofile

# 
# 
# What is this file doing?
# 
# 
    # 1. finding the "enter_virkshop" file
    # 2. trying to install nix (this is the guesses-have-to-be-made part)
    # 3. execute the "enter_virkshop" file with a specific executable

{ # <- Prevent execution if this script was only partially downloaded

# dependencies (some depend on the OS): command, uname, echo, printf, cat, read, dirname, uname, chmod, sh, sed, curl, sw_vers, pidof, whoami, mktemp, rm, basename, xz, mkdir, tar

# TODO: later add a basic check for all universally-essential commands here

# 
# fix the windows WSL mkfifo problem
# 
if [ -d "/mnt/c" ]
then
    # create some helpers
    move_out_of_the_way () {
        if [[ -e "$1" ]]
        then
            # if something is in the way, move it out of the way
            # (recursively)
            if [[ -e "$1.old" ]]
            then
                move_out_of_the_way "$1.old"
            fi
            
            # now that anything that would be in the way has been moved
            mv "$1" "$1.old"
        fi
    }
    prev_command_successful () {
        return $?
    }
    
    # 
    # check for mounting with metadata
    # 
    
    # check if metadata enabled already
    if ! mount -l | grep 'C: on /mnt/c' | grep 'metadata' &>/dev/null
    then
        echo '__________________________________________________________________________________'
        echo '|                                                                                |'
        echo '|  Howdy!                                                                        |'
        echo '|                                                                                |'
        echo '|  Looks like there`s a metadata hiccup/problem. It seems you`re using WSL       |'
        echo '|  Sadly, for some reason, WSL doesn`t (by default) support many features of the |'
        echo '|  linux file system. And For some reason, adding that support requires          |'
        echo '|  re-mounting the C drive (within WSL) with metadata enabled.                   |'
        echo '|                                                                                |'
        echo '|  I`ll run the command automatically, but if you don`t want to put              |'
        echo '|  your password in, cancel this (CTRL+C) and run the following yourself:        |'
        echo '|                                                                                |'
        echo '      {                                                                           '
        echo '          cd ; sudo umount /mnt/c && sudo mount -t drvfs C: /mnt/c -o metadata    '
        echo '      }                                                                           '
        echo '|                                                                                |'
        echo '|  Then re-run this script                                                       |'
        echo '|  You can read more about this problem here if you like:                        |'
        echo '|  https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/      |'
        echo '|                                                                                |'
        echo '----------------------------------------------------------------------------------'
        echo
        echo "Continue?"; read _
        # this means we need to unmount and remount with metadata enabled
        {
            cd && sudo umount /mnt/c && sudo mount -t drvfs C: /mnt/c -o metadata
        }
        # the cd command will be undone/ignored externally because its in a subshell (the {}'s)
    fi
    
    # if project is inside the windows C drive
    if [[ "$FORNIX_FOLDER" == "/mnt/c"* ]]; then
        echo '__________________________________________________________________________________'
        echo '|                                                                                |'
        echo '|  Howdy!                                                                        |'
        echo '|                                                                                |'
        echo '|  Looks like your project is saved in the windows file system                   |'
        echo '|  (instead of the Linux/WSL file system)                                        |'
        echo '|                                                                                |'
        echo '|  This is a bit of a problem since the file systems of                          |'
        echo '|  Linux/Mac/Android/ChromeBook/OpenBSD/etc have many features                   |'
        echo '|  that the windows file system does not have.                                   |'
        echo '|                                                                                |'
        echo '|  Would it be okay if I move this project?                                      |'
        echo '|      I`ll create a shortcut to it so you can still find it.                    |'
        echo '|      https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/  |'
        echo '|                                                                                |'
        echo '----------------------------------------------------------------------------------'
        echo
        question="[y/n]: ";answer=''
        while true; do
            echo "$question"; read response
            case "$response" in
                [Yy]* ) answer='yes'; break;;
                [Nn]* ) answer='no'; break;;
                * ) echo "Please answer yes or no.";;
            esac
        done
        if [ "$answer" = 'no' ]; then
            echo '
            
            okay, in that case just re-run this command whenever
            you have moved the project to the linux file system
                
                if you`re confused about what that^ means
                take a look at the "fornix_framework.md" file inside
                of the "documentation" folder (inside of this project folder)
            '
            exit
        else
            # 
            # where to move project
            # 
            new_project_location="$HOME/repos/$(basename "$FORNIX_FOLDER")"
            while true; do
                question="Is it okay if I move the project to '$new_project_location'? [y/n]";answer=''
                while true; do
                    echo "$question"; read response
                    case "$response" in
                        [Yy]* ) answer='yes'; break;;
                        [Nn]* ) answer='no'; break;;
                        * ) echo "Please answer yes or no.";;
                    esac
                done
                if [ "$answer" = 'no' ]; then
                    echo ""
                    echo "Where would you like to put it?"
                    echo "(press enter when done typing the path):"
                    echo ""
                    read new_project_location
                else
                    break
                fi
            done
            
            # 
            # move the project
            # 
            
            # if something is in the way, move it out of the way
            if [ -e "$new_project_location" ]
            then
                move_out_of_the_way "$new_project_location"
            fi
            
            # make sure the parent folder exists
            mkdir -p "$(dirname "$new_project_location")"
            
            # move the project itself
            prev_command_successful && mv "$FORNIX_FOLDER" "$new_project_location"
            
            # create a shortcut to the project
            prev_command_successful && ln -s "$new_project_location" "$FORNIX_FOLDER"
            
            # cd and start the project
            prev_command_successful && cd "$new_project_location" && "$new_project_location/commands/start"
            # note: commands/start is needed in the above command so the FORNIX_FOLDER and other checks/setup can be redone
            # so just exit right after because this script has become just a wrapper at this point
            exit $?
        fi
    fi
fi

# 
# 
# Setup colors
# 
# 
newline='
'
# do-nothing functions
black      () { :; }
red        () { :; }
green      () { :; }
yellow     () { :; }
blue       () { :; }
magenta    () { :; }
cyan       () { :; }
white      () { :; }
color_reset() { :; }
# if tput exists
if [ -n "$(command -v "tput")" ]
then
    black      () { tput setaf 0; }
    red        () { tput setaf 1; }
    green      () { tput setaf 2; }
    yellow     () { tput setaf 3; }
    blue       () { tput setaf 4; }
    magenta    () { tput setaf 5; }
    cyan       () { tput setaf 6; }
    white      () { tput setaf 7; }
    color_reset() { tput sgr0; }
fi

# 
# 
# Color Test
# 
#
color_test_cache_location="$HOME/.config/answered_questions/does_color_test_work"
# check if already answered this questions
if [ -f "$color_test_cache_location" ]
then
    ANSWER="$(cat "$color_test_cache_location")"
fi
# ensure the answer is well-formed
while true; do
    case "$ANSWER" in
        [Yy]* ) ANSWER='yes'; break;;
        [Nn]* ) ANSWER='no'; break;;
        * ) echo "${newline}Please answer yes or no. ${newline}";;
    esac
    echo "                                   "
    echo "               COLOR TEST              "
    echo "          |------------------|"
    echo "          |     $(red) red $(color_reset)        |"
    echo "          |     $(green) green $(color_reset)      |"
    echo "          |     $(yellow) yellow $(color_reset)     |"
    echo "          |     $(blue) blue $(color_reset)       |"
    echo "          |     $(magenta) magenta $(color_reset)    |"
    echo "          |     $(cyan) cyan $(color_reset)       |"
    echo "          |------------------|"
    echo "     
          Does this look good?
  (there should be one color per line)
    "; printf "yes/no:";
    read ANSWER
done

# create the cache file
mkdir -p "$(dirname "$color_test_cache_location")"
echo "$ANSWER" > "$color_test_cache_location"
# NOTE: this^ doesn't cover the edgecase of one of the parent "folders"
#       actually being a file, which would cause a failure
#       in the future lets plan to do a corruption check on this structure

# 
# if colors don't work/look good
# 
if [ "$answer" = 'no' ]
then
    echo " :( Okay I'll disable color"
    black      () { :; }
    red        () { :; }
    green      () { :; }
    yellow     () { :; }
    blue       () { :; }
    magenta    () { :; }
    cyan       () { :; }
    white      () { :; }
    color_reset() { :; }
fi


# 
# if nix doesnt exist
# 
if [ -z "$(command -v "nix")" ]
then
    echo "|------------------------------------------------------|"
    echo "|                                                      |"
    echo "|    I'll try to install nix for you                   |"
    echo "|    (since I don't see nix yet)                       |"
    echo "|                                                      |"
    echo "|------------------------------------------------------|"
    echo ""
    # check for root
    if [ "$(whoami)" = "root" ]
    then
        echo "$(yellow)"
        echo "looks like you're logged in as root"
        echo "sadly nix can't install on the root user"
        echo "please use a regular user, then re-run this script"
        echo "$(color_reset)"
        # if users exists
        if [ -n "$(command -v "cut")" ]
        then
            users="$(grep '^sudo:.*$' /etc/group | cut -d: -f4)"
            if [ -n "$users" ] && [ "$users" != "root" ] && [ "$users" != "root root" ]
            then
                echo "the available users are:"
                grep '^sudo:.*$' /etc/group | cut -d: -f4
                echo "you should be able to run $(cyan)su $(yellow)USER_NAME$(color_reset)"
                echo "to login as one of those users"
            else
                echo ""
                echo "it looks like this system doesn't have any regular users"
                
                # if useradd exists
                if [ -n "$(command -v "useradd")" ]
                then
                    question="do you want me to make a regular user for you? [y/n]";answer=''
                    while true; do
                        echo "$question"; read response
                        case "$response" in
                            [Yy]* ) answer='yes'; break;;
                            [Nn]* ) answer='no'; break;;
                            * ) echo "Please answer yes or no.";;
                        esac
                    done
                    
                    if [ "$answer" = 'yes' ]; then
                        echo "$(magenta)Enter a username:$(color_reset)"
                        read username
                        if sudo useradd --create-home "$username" --password "password" --groups sudo
                        then
                            echo ""
                            echo "user created successfully"
                            echo "run:"
                            echo "    $(cyan)sudo passwd "$username"$(color_reset)"
                            echo "to set the password"
                        else
                            echo ""
                            echo "Sorry, there was an error when creating the user"
                            echo "I used this command: $(cyan)sudo useradd --create-home "'"'"$username"'"'" --password 'password' --groups sudo$(color_reset)"
                        fi
                    else
                        echo "Okay"
                    fi
                fi
                
            fi
        fi
        echo ""
        echo "login as the non-root user ($(cyan)su USERNAME$(color_reset))"
        echo "then re-run this command"
        exit
    fi
    #       
    # MacOS 
    #
    if [ "$(uname)" = "Darwin" ]
    then
        debugging_info="$debugging_info$newline""I think you have a Mac because "'"$OSTYPE" = "darwin"*'" came back true"
        full_version="$(sw_vers -productVersion)"
        major_version="$(echo "$full_version" | sed -E 's/([0-9]+)\.[0-9]+\.[0-9]+/\1/g')"
        minor_version="$(echo "$full_version" | sed -E 's/[0-9]+\.([0-9]+)\.[0-9]+/\1/g')"
        #                  
        # Big Sur or Newer
        #                 
        if [ "$major_version" = "11" ]; then
            sh <(curl -Lk https://releases.nixos.org/nix/nix-2.3.8/install) --darwin-use-unencrypted-nix-store-volume
        #                  
        # Older than Big Sur (Catalina, Mojave, High Siera, Siera, etc)
        #                 
        elif [ "$major_version" -eq "10" ]; then
            # Catalina
            if [ "$minor_version" = "15" ]; then
                sh <(curl -Lk https://releases.nixos.org/nix/nix-2.3.8/install) --darwin-use-unencrypted-nix-store-volume
            # Mojave, High Siera, Siera, and might work on even older versions (Yosemite, Mavericks)
            else
                curl -Lk https://releases.nixos.org/nix/nix-2.3.8/install | sh -s -- --daemon
            fi
        else
            echo 'We tried to get you MacOS version by running `sw_vers -productVersion`'
            echo '(which returns '"$full_version"')'
            echo "Either 1. that value is empty 2. You're on an insanely old version 3. You're on a version way way in the future from when this script was made"
        fi
    # assuming Linux/POSIX if not on MacOS
    else
        # if curl doesnt exist, try to make it exist
        if [ -z "$(command -v "curl")" ]
        then
            # if apt-get exists
            if [ -n "$(command -v "apt-get")" ]
            then
                sudo apt-get update && sudo apt-get install curl
            else
                echo "it looks like you don't have curl, please install curl then re-run this script" 1>&2
                echo "alternatively, to get nix, manually run the commands inside https://releases.nixos.org/nix/nix-2.3.8/install" 1>&2
            fi
        fi
        
        # if now curl exists
        if [ -n "$(command -v "curl")" ]
        then
            # prefer single-user (no shell reload)
            curl -L https://releases.nixos.org/nix/nix-2.3.8/install | sh -s
            # # check if systemd exists
            # if pidof systemd
            # then
            #     # multi-user install if systemd exists
            #     curl -Lk https://releases.nixos.org/nix/nix-2.3.8/install | sh -s -- --daemon
            # else
            #     # single-user install if systemd exists
            #     curl -L https://releases.nixos.org/nix/nix-2.3.8/install | sh
            #     # curl -Lk https://releases.nixos.org/nix/nix-2.3.8/install | sh -s
            # fi
        fi
    fi
fi

# 
# if nix was not installed
# 
if ! [ -d "/nix/store" ]
then
    echo "$(yellow)"
    echo "|-- Problem ------------------------------------------------------------------------------------| $(color_reset)" 1>&2
    echo "|                                                                                               |" 1>&2
    echo "|    Looks like there was a problem installing nix :/                                           |" 1>&2
    echo "|    Hopefully there are error messages above                                                   |" 1>&2
    echo "|    If you want additional information about installing nix see:                               |" 1>&2
    echo "|         https://nixos.org/manual/nix/stable/#chap-installation                                |" 1>&2
    echo "|                                                                                               |" 1>&2
    echo "|-----------------------------------------------------------------------------------------------|" 1>&2
    echo ""
    exit
# if nix was installed (hopefully successfully)
else
    # 
    # manually update the shell environment 
    # 
    if [ -f "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh" ]
    then
        . "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
    fi
    if [ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ]
    then
        . "$HOME/.nix-profile/etc/profile.d/nix.sh"
    fi
    export PATH="$PATH:/nix/var/nix/profiles/default/bin/"
    
    # if nix-env doesnt exist
    if [ -z "$(command -v "nix-env")" ] || [ -z "$(command -v "nix-shell")" ]
    then
        echo "$(yellow)"
        echo "|-- Action Needed ------------------------------------------------------------------------------| $(color_reset)" 1>&2
        echo "|                                                                                               |" 1>&2
        echo "|    - Try closing/reopening your terminal and running this command again                       |" 1>&2
        echo "|      (I dont see the nix-env and nix-shell command)                                           |" 1>&2
        echo "|                                                                                               |" 1>&2
        echo "|    - If you already did that, and you're still getting this message                           |" 1>&2
        echo "|      then you might need to uninstall and reinstall nix                                       |" 1>&2
        echo "|      instructions here:                                                                       |" 1>&2
        echo "|         https://nixos.org/manual/nix/stable/#sect-single-user-installation                    |" 1>&2
        echo "|                                                                                               |" 1>&2
        echo "|-----------------------------------------------------------------------------------------------|" 1>&2
        echo ""
        exit
    fi
fi

# 
# 
# Nix should now be installed => Enter the virkshop!
# 
# 

# 
# Find our virkshop config
# 
path_to_virkshop_config=""
file_name="virkshop/internals/configuration"
folder_to_look_in="$PWD"
while :
do
    # check if file exists
    if [ -e "$folder_to_look_in/$file_name" ]
    then
        path_to_virkshop_config="$folder_to_look_in/$file_name"
        break
    else
        if [ "$folder_to_look_in" = "/" ]
        then
            break
        else
            folder_to_look_in="$(dirname "$folder_to_look_in")"
        fi
    fi
done
if [ -z "$path_to_virkshop_config" ]
then
    #
    # what to do if file never found
    #
    echo "$(yellow)"
    echo "|-- Problem -------------------------------------------------------------| $(color_reset)" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|    Looks like you have nix installed (that's good)                     |" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|    However, I can't find the virkshop/internals/configuration folder   |" 1>&2
    echo "|    I started looking in your current folder                            |" 1>&2
    echo "|         current directory is: '$PWD'                                 " 1>&2
    echo "|    I also looked in all the parent folders, but couldn't find it       |" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|    todo:                                                               |" 1>&2
    echo "|      - make sure you're in the right folder (likely to be the problem) |" 1>&2
    echo "|      - make sure the virkshop folder isn't corrupted (re-download)     |" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|------------------------------------------------------------------------|" 1>&2
    echo ""
    # TODO: in the future, offer to redownload (encase the script is being run directly from curl)
    # TODO: in the future, check if already inside of a virkshop (accidentally doing virkshop inception)
    exit
fi

# 
# find virkshop entrypoint
# 
export VIRKSHOP_FOLDER="$path_to_virkshop_config/../../"
path_to_virkshop_entry="$VIRKSHOP_FOLDER/$(cat "$path_to_virkshop_config/path_to/entry_point")"
# TODO: add a check to make sure the config isn't corrupt

# 
# check if entry_point exists
# 
if ! [ -f "$path_to_virkshop_entry" ]
then
    echo "$(yellow)"
    echo "|-- Problem -------------------------------------------------------------| $(color_reset)" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|    I was looking for the virkshop entry_point but I couldnt find it    |" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|    The config (virkshop/internals/configuration/path_to/entry_point)   |" 1>&2
    echo "|    says that the file is at: '$path_to_virkshop_entry'                  " 1>&2
    echo "|    But that doesn't seem to be a file                                  |" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|    todo:                                                               |" 1>&2
    echo "|      - make sure the virkshop folder isn't corrupted (re-download)     |" 1>&2
    echo "|                                                                        |" 1>&2
    echo "|------------------------------------------------------------------------|" 1>&2
    exit
fi

# make sure the file is executable
if [ -n "$(command -v "chmod")" ]
then
    # if sudo exists
    if [ -n "$(command -v "sudo")" ]
    then
        chmod ugo+x "$path_to_virkshop_entry" 2>/dev/null || sudo chmod ugo+x "$path_to_virkshop_entry"
    # if doas exists
    elif [ -n "$(command -v "doas")" ]
    then
        chmod ugo+x "$path_to_virkshop_entry" 2>/dev/null || doas chmod ugo+x "$path_to_virkshop_entry"
    # if neither exist
    else
        chmod ugo+x "$path_to_virkshop_entry" 2>/dev/null
    fi
fi

# 
# parse and escape the arguments
# 
arguments_for_start_script="" # futureproofing encase this script needs args (verbose/debugging/alternatives to nix etc)
found_the_arg_switch=""
escaped_arguments_for_entry_file="'$(printf '%s' "$path_to_virkshop_entry" | sed 's/'"'"'/'"'"'"'"'"'"'"'"'/g')'"
for arg in "$@"; do
    # if the -- has not been found
    if [ -z "$found_the_arg_switch" ]
    then
        # if it is found
        if [ "$arg" = "--" ]
        then
            found_the_arg_switch="true"
        else
            # if in the future this script needs args this is where they would be parsed
            # for now there arent any
            true
        fi
    # once the -- has been found, the args go to the deno script
    else
        # need to escape the single quotes of each argument
        escaped_arguments_for_entry_file="$escaped_arguments_for_entry_file '$(printf '%s' "$arg" | sed 's/'"'"'/'"'"'"'"'"'"'"'"'/g')'"
    fi
done

# 
# execute enter_virkshop with a specific version of deno and pass along the arguments
# 
nix-shell --packages deno bash --run "$escaped_arguments_for_entry_file" -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz

} # end: <- Prevent execution if this script was only partially downloaded